### PR TITLE
Updating default config to use the Acquia recipe.

### PR DESCRIPTION
**Pull request by mikemadison13**

### CODE REVIEW

**Comment by mikemadison13** [comment]
blocked by https://github.com/lando/lando/issues/3095

**Comment by camoa** [comment]
Since issue 3095 from Lando seems to be unblocked, are we going to be able to use the acquia recipe now?

**Comment by mikemadison13** [comment]
thanks for the nudge @camoa! yes this is on my todo list, and I hope to have it done by the end of the month.

**Comment by camoa** [comment]
Thanks, sorry for the quick message before, I was running late to something.

**Comment by mikemadison13** [comment]
@camoa i just rebased this, i have some testing to do before i merge, but it should be safe to use this branch to give it a whirl.

**Review by sharique — APPROVED** [review]

**Pull request merged**
